services:
  api:
    container_name: api-prod
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/near05-api:${IMAGE_TAG}
    environment:
      - MODE=prod
    env_file:
      - ../envs/.prod.env
    ports:
      - "8000:8000"
    depends_on:
      db: { condition: service_healthy }
      redis: { condition: service_healthy }
    networks: [ws]
    restart: always

  db:
    image: postgres:14
    container_name: postgres-prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Seoul
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      retries: 5
    networks: [ws]
    volumes: [postgres_data:/var/lib/postgresql/data]
    restart: always

  redis:
    image: redis:7
    container_name: redis-prod
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
    networks: [ws]
    restart: always

networks:
  ws: { driver: bridge }
volumes:
  postgres_data: